In [26]:
#Importando Dataset
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving HospInfo.csv to HospInfo (3).csv

In [72]:
# Definindo o DataFrame
df = pd.read_csv('HospInfo.csv')

In [73]:
# Conferindo de carregou corretamente
df.head() # ou print(df.shape)

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote,Location
0,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Below the national average,NaN,"2505 U S HIGHWAY 431 NORTH\nBOAZ, AL\n"
1,10012,DEKALB REGIONAL MEDICAL CENTER,200 MED CENTER DRIVE,FORT PAYNE,AL,35968,DE KALB,2568453150,Acute Care Hospitals,Proprietary,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN,"200 MED CENTER DRIVE\nFORT PAYNE, AL\n"
2,10032,WEDOWEE HOSPITAL,209 NORTH MAIN STREET,WEDOWEE,AL,36278,RANDOLPH,2563572111,Acute Care Hospitals,Government - Hospital District or Authority,...,NaN,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,"209 NORTH MAIN STREET\nWEDOWEE, AL\n"
3,10095,HALE COUNTY HOSPITAL,508 GREEN STREET,GREENSBORO,AL,36744,HALE,3346243024,Acute Care Hospitals,Government - Local,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Below the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,"508 GREEN STREET\nGREENSBORO, AL\n"
4,10131,CRESTWOOD MEDICAL CENTER,ONE HOSPITAL DR SE,HUNTSVILLE,AL,35801,MADISON,2568823100,Acute Care Hospitals,Proprietary,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,"ONE HOSPITAL DR SE\nHUNTSVILLE, AL\n"

In [74]:
# Tipos de colunas
colunas_numericas = df.select_dtypes(include=['int64', 'float64']).columns
colunas_categoricas = df.select_dtypes(include=['object', 'category']).columns

print('Numericas:', colunas_numericas)
print('Categoricas:', colunas_categoricas)

Numericas: Index(['Provider ID', 'ZIP Code', 'Phone Number'], dtype='object')
Categoricas: Index(['Hospital Name', 'Address', 'City', 'State', 'County Name',
       'Hospital Type', 'Hospital Ownership',
       'Meets criteria for meaningful use of EHRs', 'Hospital overall rating',
       'Hospital overall rating footnote', 'Mortality national comparison',
       'Mortality national comparison footnote',
       'Safety of care national comparison',
       'Safety of care national comparison footnote',
       'Readmission national comparison',
       'Readmission national comparison footnote',
       'Patient experience national comparison',
       'Patient experience national comparison footnote',
       'Effectiveness of care national comparison',
       'Effectiveness of care national comparison footnote',
       'Timeliness of care national comparison',
       'Timeliness of care national comparison footnote',
       'Efficient use of medical imaging national comparison',
       'Efficient use of medical imaging national comparison footnote',
       'Location'],
      dtype='object')

In [75]:
# Valores Ausentes
print('\nValores ausentes:')
print(df.isnull().sum())

Valores ausentes:
Provider ID                                                         0
Hospital Name                                                       0
Address                                                             0
City                                                                0
State                                                               0
ZIP Code                                                            0
County Name                                                        15
Phone Number                                                        0
Hospital Type                                                       0
Hospital Ownership                                                  0
Emergency Services                                                  0
Meets criteria for meaningful use of EHRs                         144
Hospital overall rating                                             0
Hospital overall rating footnote                                 3414
Mortality national comparison                                       0
Mortality national comparison footnote                           3460
Safety of care national comparison                                  0
Safety of care national comparison footnote                      2644
Readmission national comparison                                     0
Readmission national comparison footnote                         3795
Patient experience national comparison                              0
Patient experience national comparison footnote                  3443
Effectiveness of care national comparison                           0
Effectiveness of care national comparison footnote               3610
Timeliness of care national comparison                              0
Timeliness of care national comparison footnote                  3546
Efficient use of medical imaging national comparison                0
Efficient use of medical imaging national comparison footnote    2779
Location                                                            0
dtype: int64

In [76]:
# Tratamento dos valores Ausentes
colunas_footnote = [col for col in df.columns if 'footnote' in col]
df.drop(columns=colunas_footnote, inplace=True)

# Tratar valores ausentes restantes
df['County Name'] = df['County Name'].fillna('Desconhecido')
df['Meets criteria for meaningful use of EHRs'] = df['Meets criteria for meaningful use of EHRs'].fillna('Nao informado')

# Conferindo as alteracoes
print(df.isnull().sum())

Provider ID                                             0
Hospital Name                                           0
Address                                                 0
City                                                    0
State                                                   0
ZIP Code                                                0
County Name                                             0
Phone Number                                            0
Hospital Type                                           0
Hospital Ownership                                      0
Emergency Services                                      0
Meets criteria for meaningful use of EHRs               0
Hospital overall rating                                 0
Mortality national comparison                           0
Safety of care national comparison                      0
Readmission national comparison                         0
Patient experience national comparison                  0
Effectiveness of care national comparison               0
Timeliness of care national comparison                  0
Efficient use of medical imaging national comparison    0
Location                                                0
dtype: int64

In [77]:
# Padronizando a coluna State
df['State'] = df['State'].str.strip().str.upper() #Deixando tudo em maiusculo e removendo espacos

In [78]:
# Conferindo valores unicos
df['State'].unique()

array(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI',
       'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI',
       'MN', 'MS', 'MO', 'MT', 'NE', 'PA', 'NV', 'NJ', 'NM', 'NY', 'NC',
       'ND', 'OH', 'OK', 'OR', 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT',
       'VT', 'VA', 'WA', 'WV', 'WI', 'VI', 'WY', 'AS', 'GU', 'MP', 'DC',
       'NH'], dtype=object)

In [79]:
# Padronizando tipo de hospital - Limpando texto
df['Hospital Type'] = df['Hospital Type'].str.strip().str.title()

In [80]:
df['Hospital Type'].unique() # Mostrar todos os valores sem repeticao

array(['Acute Care Hospitals', 'Critical Access Hospitals', 'Childrens'],
      dtype=object)

In [81]:
# Conferindo resultado
print('Estados únicos:', df['State'].unique())

Estados únicos: ['AL' 'AK' 'AZ' 'AR' 'CA' 'CO' 'CT' 'DE' 'FL' 'GA' 'HI' 'ID' 'IL' 'IN'
 'IA' 'KS' 'KY' 'LA' 'ME' 'MD' 'MA' 'MI' 'MN' 'MS' 'MO' 'MT' 'NE' 'PA'
 'NV' 'NJ' 'NM' 'NY' 'NC' 'ND' 'OH' 'OK' 'OR' 'PR' 'RI' 'SC' 'SD' 'TN'
 'TX' 'UT' 'VT' 'VA' 'WA' 'WV' 'WI' 'VI' 'WY' 'AS' 'GU' 'MP' 'DC' 'NH']

Criando um Dataframe com os dados por estado:

In [82]:
# Convertendo String para Numerica # Pandas ignora NaN
df['Hospital overall rating'] = pd.to_numeric(
    df['Hospital overall rating'],
    errors='coerce'
)
df['Hospital overall rating'].isnull().sum() # Conferindo

np.int64(1245)

In [83]:
# Numero de hospitais por estado
hospitais_por_estado = df.groupby('State')['Hospital Name'].count()
# Media das avaliacoes por estado
media_avaliacao = df.groupby('State')['Hospital overall rating'].mean()
# Distribuicao dos tipos de hospital
distribuicao_tipos = df.groupby(['State', 'Hospital Type']).size()

Criando DataFrame consolidado:

In [84]:
df_agg = df.groupby('State').agg({
    'Hospital Name': 'count',
    'Hospital overall rating': 'mean'
}).rename(columns={
    'Hospital Name': 'Numero de Hospitais',
    'Hospital overall rating': 'Media Avaliacao'
})
print(df_agg)

       Numero de Hospitais  Media Avaliacao
State
AK                      22         2.888889
AL                      90         3.050633
AR                      75         2.836364
AS                       1              NaN
AZ                      80         2.944444
CA                     343         2.841379
CO                      78         3.450980
CT                      31         2.714286
DC                       8         1.428571
DE                       7         3.666667
FL                     187         2.662722
GA                     133         2.935185
GU                       2         3.000000
HI                      23         3.307692
IA                     116         3.394366
ID                      41         3.526316
IL                     180         3.132075
IN                     120         3.481481
KS                     137         3.344828
KY                      94         2.975904
LA                     121         3.126582
MA                      64         3.192982
MD                      49              NaN
ME                      33         3.437500
MI                     131         3.191304
MN                     131         3.531646
MO                     112         3.011628
MP                       1              NaN
MS                      95         2.777778
MT                      62         3.347826
NC                     107         3.106383
ND                      44         3.187500
NE                      89         3.291667
NH                      26         3.480000
NJ                      66         2.546875
NM                      41         2.709677
NV                      35         2.400000
NY                     171         2.320261
OH                     168         3.378571
OK                     124         3.148148
OR                      60         3.153846
PA                     171         3.006803
PR                      52         2.111111
RI                      11         3.272727
SC                      60         3.192308
SD                      60         3.857143
TN                     107         2.870968
TX                     411         3.231061
UT                      46         3.448276
VA                      86         3.013158
VI                       2         2.000000
VT                      14         3.250000
WA                      91         3.015152
WI                     126         3.611111
WV                      49         2.756757
WY                      28         3.000000

Criando uma nova variavel categorica para classificar os hospitais em 3 niveis de qualdiade:

In [85]:
# Defininindo criterios
def classificar_qualidade(nota):
  if nota <= 2:
      return 'Baixa'
  elif nota == 3:
      return 'Media'
  elif nota >= 4:
      return 'Alta'
  else:
      return 'Nao Avaliado'
df['Nivel de Qualidade'] = df['Hospital overall rating'].apply(classificar_qualidade)

# Conferindo resultado
df[['Hospital overall rating', 'Nivel de Qualidade']].head()

   Hospital overall rating Nivel de Qualidade
0                      3.0              Media
1                      3.0              Media
2                      4.0               Alta
3                      NaN       Nao Avaliado
4                      3.0              Media

In [86]:
df['Nivel de Qualidade'].value_counts()

Nivel de Qualidade
Media           1761
Nao Avaliado    1245
Alta            1021
Baixa            785
Name: count, dtype: int64